@startuml
!include style.puml

box RankCommand LOGIC_COLOR_T1
participant ":RankCommand" as RankCommand LOGIC_COLOR
participant ":OutOfSessionCommandException" as OutSessionException LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

activate RankCommand

alt no ongoing competition session
    create OutSessionException
    RankCommand -> OutSessionException
    activate OutSessionException
    OutSessionException --> RankCommand
    deactivate OutSessionException

else athlete not in a competition session
    create CommandResult
    RankCommand -> CommandResult
    activate CommandResult
    CommandResult --> RankCommand: Competition session has not athlete
    deactivate CommandResult

else athlete is present in a competition session
    create CommandResult
    RankCommand -> CommandResult
    activate CommandResult
    CommandResult --> RankCommand: Athlete's report card in competition
    deactivate CommandResult

end
deactivate RankCommand

@enduml